services:
  - type: web
    name: tennisviz-analytics
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: ENVIRONMENT
        value: "production"
    autoDeploy: true
